theme: jekyll-theme-cayman
title: HDR Image Reconstruction and Tone Mapping (CS766 Final Project)
description: Welcome to my CS766 final project page. This page contains the summary and some technical details of the project.
