theme: jekyll-theme-cayman
.page__content {
  text-align: justify;
}
title: HDR Image Reconstruction and Tone Mapping
description: Welcome to my CS766 final project page. This page contains the summary and some technical details of the project.
